### ISSUE TITLE
Multivariate mixed model using lme4

### ISSUE THREAD

**Issue by FrancoiseCardou** [bbolker/mixedmodels-misc#11]
Hello, 

This isn't so much an issue as a question, so, apologies if this isn't quite the right forum for this.

I'm using lme4 to fit mixed models for "melted" multivariate data, and including a new variable in both the fixed and random components of my model to capture the repeated measure element of this dataset. The vignette that I originally followed to figure out model structure used to be available at the following location, but doesn't appear to be online anymore.

Bolker, B. (2019). Multivariate modeling via mixed models. https://mac-theobio.github.io/QMEE/MultivariateMixed.html (last accessed ca. July, 2020)

If possible, I'd like to be able to cite this vignette formally, and I was wondering if it had been relocated or if it was expected to come back online at any point?

Thanks for any help!

Françoise

**Comment by bbolker** [comment]
Is this it?

Is this what you're looking for

https://mac-theobio.github.io/QMEE/lectures/MultivariateMixed.notes.html

?

**Comment by FrancoiseCardou** [comment]
Yes! Much appreciated, thank you!

Françoise
