### ISSUE TITLE
brms

### ISSUE THREAD

**Issue by jerlich** [bbolker/mixedmodels-misc#4]
Thanks for this FAQ.

Small point: `brms` can fit linear, generalized linear, and non-linear models.
So, maybe just put it in it's own list?

**Comment by bbolker** [comment]
The intro section now reads

---
The most commonly used functions for mixed modeling in R are

- *linear mixed models*: `aov()`, `nlme::lme`[^1], `lme4::lmer`;
- *generalized linear mixed models* (GLMMs)
    - frequentist: `MASS::glmmPQL`, `lme4::glmer`; `glmmTMB`
    - Bayesian: `MCMCglmm::MCMCglmm`; `brms::brm`
- *nonlinear mixed models*: `nlme::nlme`, `lme4::nlmer`; `brms::brm`
- *GNLMMs*: `brms::brm`
---

Is that something like what you had in mind?
