### ISSUE TITLE
problem with the github io page?

### ISSUE THREAD

**Issue by melina-leite** [bbolker/mixedmodels-misc#6]
Dear Prof. Bolker,
I've found this message while trying to open the [url](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html) of the io page of this repository:

> Error 503 Maximum threads for service reached
> 
> Maximum threads for service reached
> Guru Mediation:
> 
> Details: cache-gru17132-GRU 1553107448 3476438191
> 
> Varnish cache server

I would like to send it to a friend that will not understand the Rmd code in GitHub easily. 
Is it a problem with my browser or something went wrong with the website?

Thank you!

**Comment by bbolker** [comment]
I guess it cleared up?

**Comment by melina-leite** [comment]
Yes!! Thank you very much!
